package com.fleetMall.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("bill_records", "uuid", BillRecords.class);
		arp.addMapping("boss", "uuid", Boss.class);
		arp.addMapping("comment", "uuid", Comment.class);
		arp.addMapping("commodity", "uuid", Commodity.class);
		arp.addMapping("employee", "uuid", Employee.class);
		arp.addMapping("message", "uuid", Message.class);
		arp.addMapping("photos", "uuid", Photos.class);
		arp.addMapping("price_alter", "uuid", PriceAlter.class);
		arp.addMapping("road_condition", "uuid", RoadCondition.class);
		arp.addMapping("store", "uuid", Store.class);
	}
}

