package com.fleetMall.model;

import com.fleetMall.model.base.BaseBillRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BillRecords extends BaseBillRecords<BillRecords> {
	public static final BillRecords dao = new BillRecords().dao();
}
