package com.fleetMall.model;

import com.fleetMall.model.base.BaseBoss;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Boss extends BaseBoss<Boss> {
	public static final Boss dao = new Boss().dao();
}
