package com.fleetMall.model;

import com.fleetMall.model.base.BaseCommodity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Commodity extends BaseCommodity<Commodity> {
	public static final Commodity dao = new Commodity().dao();
}
