package com.fleetMall.model;

import com.fleetMall.model.base.BaseEmployee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Employee extends BaseEmployee<Employee> {
	public static final Employee dao = new Employee().dao();

	public Employee checkEmployeeInfomation(String userTelephone, String password) {
		String sql = "select * from employee where employee_telephone = '" + userTelephone + "' and employee_password = '" + password + "'";
		Employee employee = null;
		if (find(sql) != null) {
			employee = (Employee) find(sql);
			return employee;
		} else {
			return null;
		}
	}
}
