package com.fleetMall.model;

import com.fleetMall.model.base.BasePhotos;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Photos extends BasePhotos<Photos> {
	public static final Photos dao = new Photos().dao();
}
