package com.fleetMall.model;

import com.fleetMall.model.base.BasePriceAlter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PriceAlter extends BasePriceAlter<PriceAlter> {
	public static final PriceAlter dao = new PriceAlter().dao();
}
