package com.fleetMall.model;

import com.fleetMall.model.base.BaseRoadCondition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoadCondition extends BaseRoadCondition<RoadCondition> {
	public static final RoadCondition dao = new RoadCondition().dao();
}
