package com.fleetMall.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRoadCondition<M extends BaseRoadCondition<M>> extends Model<M> implements IBean {

	public M setUuid(java.lang.String uuid) {
		set("uuid", uuid);
		return (M)this;
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public M setRoadConditionContent(java.lang.String roadConditionContent) {
		set("road_condition_content", roadConditionContent);
		return (M)this;
	}

	public java.lang.String getRoadConditionContent() {
		return get("road_condition_content");
	}

	public M setRoadConditionTitle(java.lang.String roadConditionTitle) {
		set("road_condition_title", roadConditionTitle);
		return (M)this;
	}

	public java.lang.String getRoadConditionTitle() {
		return get("road_condition_title");
	}

	public M setIsDelete(java.lang.Integer isDelete) {
		set("isDelete", isDelete);
		return (M)this;
	}

	public java.lang.Integer getIsDelete() {
		return get("isDelete");
	}

	public M setParentUuid(java.lang.String parentUuid) {
		set("parent_uuid", parentUuid);
		return (M)this;
	}

	public java.lang.String getParentUuid() {
		return get("parent_uuid");
	}

	public M setRoadConditionDateTime(java.lang.String roadConditionDateTime) {
		set("road_condition_date_time", roadConditionDateTime);
		return (M)this;
	}

	public java.lang.String getRoadConditionDateTime() {
		return get("road_condition_date_time");
	}

	public M setRoadPositionX(java.lang.String roadPositionX) {
		set("road_position_x", roadPositionX);
		return (M)this;
	}

	public java.lang.String getRoadPositionX() {
		return get("road_position_x");
	}

	public M setRoadPositionY(java.lang.String roadPositionY) {
		set("road_position_y", roadPositionY);
		return (M)this;
	}

	public java.lang.String getRoadPositionY() {
		return get("road_position_y");
	}

}
