package com.fleetMall.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public M setUuid(java.lang.String uuid) {
		set("uuid", uuid);
		return (M)this;
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public M setCommentContent(java.lang.String commentContent) {
		set("comment_content", commentContent);
		return (M)this;
	}

	public java.lang.String getCommentContent() {
		return get("comment_content");
	}

	public M setCommentDateTime(java.lang.String commentDateTime) {
		set("comment_date_time", commentDateTime);
		return (M)this;
	}

	public java.lang.String getCommentDateTime() {
		return get("comment_date_time");
	}

	public M setCommentUserName(java.lang.String commentUserName) {
		set("comment_user_name", commentUserName);
		return (M)this;
	}

	public java.lang.String getCommentUserName() {
		return get("comment_user_name");
	}

	public M setCommodityUuid(java.lang.String commodityUuid) {
		set("commodity_uuid", commodityUuid);
		return (M)this;
	}

	public java.lang.String getCommodityUuid() {
		return get("commodity_uuid");
	}

	public M setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

}
