package com.fleetMall.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public M setUuid(java.lang.String uuid) {
		set("uuid", uuid);
		return (M)this;
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public M setHasRead(java.lang.Boolean hasRead) {
		set("has_read", hasRead);
		return (M)this;
	}

	public java.lang.Boolean getHasRead() {
		return get("has_read");
	}

	public M setIsDelete(java.lang.Integer isDelete) {
		set("isDelete", isDelete);
		return (M)this;
	}

	public java.lang.Integer getIsDelete() {
		return get("isDelete");
	}

	public M setMessageContent(java.lang.String messageContent) {
		set("message_content", messageContent);
		return (M)this;
	}

	public java.lang.String getMessageContent() {
		return get("message_content");
	}

	public M setMessageDateTime(java.lang.String messageDateTime) {
		set("message_date_time", messageDateTime);
		return (M)this;
	}

	public java.lang.String getMessageDateTime() {
		return get("message_date_time");
	}

	public M setReceiverUuid(java.lang.String receiverUuid) {
		set("receiver_uuid", receiverUuid);
		return (M)this;
	}

	public java.lang.String getReceiverUuid() {
		return get("receiver_uuid");
	}

	public M setSenderUuid(java.lang.String senderUuid) {
		set("sender_uuid", senderUuid);
		return (M)this;
	}

	public java.lang.String getSenderUuid() {
		return get("sender_uuid");
	}

}
