package com.fleetMall.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBillRecords<M extends BaseBillRecords<M>> extends Model<M> implements IBean {

	public M setUuid(java.lang.String uuid) {
		set("uuid", uuid);
		return (M)this;
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public M setActualOutlay(java.lang.String actualOutlay) {
		set("actual_outlay", actualOutlay);
		return (M)this;
	}

	public java.lang.String getActualOutlay() {
		return get("actual_outlay");
	}

	public M setBillDate(java.lang.String billDate) {
		set("bill_date", billDate);
		return (M)this;
	}

	public java.lang.String getBillDate() {
		return get("bill_date");
	}

	public M setBillStatus(java.lang.String billStatus) {
		set("bill_status", billStatus);
		return (M)this;
	}

	public java.lang.String getBillStatus() {
		return get("bill_status");
	}

	public M setBossUuid(java.lang.String bossUuid) {
		set("boss_uuid", bossUuid);
		return (M)this;
	}

	public java.lang.String getBossUuid() {
		return get("boss_uuid");
	}

	public M setCommodityUuid(java.lang.Long commodityUuid) {
		set("commodity_uuid", commodityUuid);
		return (M)this;
	}

	public java.lang.Long getCommodityUuid() {
		return get("commodity_uuid");
	}

	public M setEmployeeUuid(java.lang.String employeeUuid) {
		set("employee_uuid", employeeUuid);
		return (M)this;
	}

	public java.lang.String getEmployeeUuid() {
		return get("employee_uuid");
	}

	public M setIsDelete(java.lang.Integer isDelete) {
		set("isDelete", isDelete);
		return (M)this;
	}

	public java.lang.Integer getIsDelete() {
		return get("isDelete");
	}

}
