package com.fleetMall.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePhotos<M extends BasePhotos<M>> extends Model<M> implements IBean {

	public M setUuid(java.lang.String uuid) {
		set("uuid", uuid);
		return (M)this;
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public M setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public M setParentUuid(java.lang.String parentUuid) {
		set("parent_uuid", parentUuid);
		return (M)this;
	}

	public java.lang.String getParentUuid() {
		return get("parent_uuid");
	}

	public M setPhotoUrl(java.lang.String photoUrl) {
		set("photo_url", photoUrl);
		return (M)this;
	}

	public java.lang.String getPhotoUrl() {
		return get("photo_url");
	}

}
