package com.fleetMall.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEmployee<M extends BaseEmployee<M>> extends Model<M> implements IBean {

	public M setUuid(java.lang.String uuid) {
		set("uuid", uuid);
		return (M)this;
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public M setArrears(java.lang.String arrears) {
		set("arrears", arrears);
		return (M)this;
	}

	public java.lang.String getArrears() {
		return get("arrears");
	}

	public M setBossUuid(java.lang.String bossUuid) {
		set("boss_uuid", bossUuid);
		return (M)this;
	}

	public java.lang.String getBossUuid() {
		return get("boss_uuid");
	}

	public M setCarNumber(java.lang.String carNumber) {
		set("car_number", carNumber);
		return (M)this;
	}

	public java.lang.String getCarNumber() {
		return get("car_number");
	}

	public M setEmployeeImageUrl(java.lang.String employeeImageUrl) {
		set("employee_image_url", employeeImageUrl);
		return (M)this;
	}

	public java.lang.String getEmployeeImageUrl() {
		return get("employee_image_url");
	}

	public M setEmployeeName(java.lang.String employeeName) {
		set("employee_name", employeeName);
		return (M)this;
	}

	public java.lang.String getEmployeeName() {
		return get("employee_name");
	}

	public M setEmployeePassword(java.lang.String employeePassword) {
		set("employee_password", employeePassword);
		return (M)this;
	}

	public java.lang.String getEmployeePassword() {
		return get("employee_password");
	}

	public M setEmployeeRemainMoney(java.lang.String employeeRemainMoney) {
		set("employee_remain_money", employeeRemainMoney);
		return (M)this;
	}

	public java.lang.String getEmployeeRemainMoney() {
		return get("employee_remain_money");
	}

	public M setEmployeeTelephone(java.lang.String employeeTelephone) {
		set("employee_telephone", employeeTelephone);
		return (M)this;
	}

	public java.lang.String getEmployeeTelephone() {
		return get("employee_telephone");
	}

	public M setIsDelete(java.lang.Integer isDelete) {
		set("isDelete", isDelete);
		return (M)this;
	}

	public java.lang.Integer getIsDelete() {
		return get("isDelete");
	}

	public M setPayPassword(java.lang.String payPassword) {
		set("pay_password", payPassword);
		return (M)this;
	}

	public java.lang.String getPayPassword() {
		return get("pay_password");
	}

	public M setRegisterDateTime(java.lang.String registerDateTime) {
		set("register_date_time", registerDateTime);
		return (M)this;
	}

	public java.lang.String getRegisterDateTime() {
		return get("register_date_time");
	}

}
