package com.fleetMall.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBoss<M extends BaseBoss<M>> extends Model<M> implements IBean {

	public M setUuid(java.lang.String uuid) {
		set("uuid", uuid);
		return (M)this;
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public M setArrears(java.lang.String arrears) {
		set("arrears", arrears);
		return (M)this;
	}

	public java.lang.String getArrears() {
		return get("arrears");
	}

	public M setBossImgUrl(java.lang.String bossImgUrl) {
		set("boss_img_url", bossImgUrl);
		return (M)this;
	}

	public java.lang.String getBossImgUrl() {
		return get("boss_img_url");
	}

	public M setBossName(java.lang.String bossName) {
		set("boss_name", bossName);
		return (M)this;
	}

	public java.lang.String getBossName() {
		return get("boss_name");
	}

	public M setBossPassword(java.lang.String bossPassword) {
		set("boss_password", bossPassword);
		return (M)this;
	}

	public java.lang.String getBossPassword() {
		return get("boss_password");
	}

	public M setBossRemainMoney(java.lang.String bossRemainMoney) {
		set("boss_remain_money", bossRemainMoney);
		return (M)this;
	}

	public java.lang.String getBossRemainMoney() {
		return get("boss_remain_money");
	}

	public M setBossTelephone(java.lang.String bossTelephone) {
		set("boss_telephone", bossTelephone);
		return (M)this;
	}

	public java.lang.String getBossTelephone() {
		return get("boss_telephone");
	}

	public M setCarNumber(java.lang.String carNumber) {
		set("car_number", carNumber);
		return (M)this;
	}

	public java.lang.String getCarNumber() {
		return get("car_number");
	}

	public M setIsDelete(java.lang.Integer isDelete) {
		set("isDelete", isDelete);
		return (M)this;
	}

	public java.lang.Integer getIsDelete() {
		return get("isDelete");
	}

	public M setPayPassword(java.lang.String payPassword) {
		set("pay_password", payPassword);
		return (M)this;
	}

	public java.lang.String getPayPassword() {
		return get("pay_password");
	}

	public M setRegisterDateTime(java.lang.String registerDateTime) {
		set("register_date_time", registerDateTime);
		return (M)this;
	}

	public java.lang.String getRegisterDateTime() {
		return get("register_date_time");
	}

}
