package com.fleetMall.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCommodity<M extends BaseCommodity<M>> extends Model<M> implements IBean {

	public M setUuid(java.lang.String uuid) {
		set("uuid", uuid);
		return (M)this;
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public M setCommodityIntroduction(java.lang.String commodityIntroduction) {
		set("commodity_introduction", commodityIntroduction);
		return (M)this;
	}

	public java.lang.String getCommodityIntroduction() {
		return get("commodity_introduction");
	}

	public M setCommodityName(java.lang.String commodityName) {
		set("commodity_name", commodityName);
		return (M)this;
	}

	public java.lang.String getCommodityName() {
		return get("commodity_name");
	}

	public M setCommodityPrice(java.lang.String commodityPrice) {
		set("commodity_price", commodityPrice);
		return (M)this;
	}

	public java.lang.String getCommodityPrice() {
		return get("commodity_price");
	}

	public M setCommodityType(java.lang.String commodityType) {
		set("commodity_type", commodityType);
		return (M)this;
	}

	public java.lang.String getCommodityType() {
		return get("commodity_type");
	}

	public M setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public M setStoreUuid(java.lang.String storeUuid) {
		set("store_uuid", storeUuid);
		return (M)this;
	}

	public java.lang.String getStoreUuid() {
		return get("store_uuid");
	}

}
